version: 0.2
phases:
  install:
    commands:
      - cd postman/01api
      - aws cloudformation package --template-file petstore-api.yaml
                                   --s3-bucket codepipeline-with-postman
                                   --s3-prefix api-code
                                   --output-template-file petstore-api-output.yaml
artifacts:
  type: zip
  files:
    - postman/01api/petstore-api-output.yaml
